[package]
name = "ytfeed"
version = "0.2.0"
edition = "2021"
authors = ["Rijk van Putten <rijk@rijkvp.nl>"]
description = "YouTube feed proxy"
readme = "README.md"
homepage = "https://github.com/rijkvp/ytfeed"
license = "AGPL-3.0"

[dependencies]
atom_syndication = "0.12"
axum = { version = "0.6", features = ["http2"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
thiserror = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
scraper = "0.16"
reqwest = { version = "0.11", default-features = false, features = [ "rustls-tls", "brotli" ] }
chrono = "0.4"
parking_lot = "0.12"
clap = { version = "4.1", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
strip = true

